split the statesync section
dydxopsdao/v4-documentation pull request #44
Opened 2023-12-19 23:16 UTC by 2dpetkov

We need to have node ID to the statesync information, not a URL to the RPC nodes - let's make some room for this.

2023-12-21 08:38 UTC, nullmames commented on pages/networks/network1/resources.md
> +| Team           | URI                                                       | Pruning |
Please add another column for index. This is important for archives.
Kingnodes archive index `kv`.
All other snapshots are likely `null` but would need to confirm with operators.

2023-12-21 08:38 UTC, nullmames commented on pages/networks/network1/resources.md
> +| Team           |  URI                                                                                  |
Please change URI to **Statesync Peers**
Please add a column for region (this may be important to some operators)

2023-12-21 08:38 UTC, nullmames commented on pages/networks/network1/resources.md
> +| KingNodes      |  |
Node 1: f94dcfbccb9019584d1790562a020507b050d9ba@51.77.56.23:23856 (EU_West)
Node 2: 6bc1068d9a257931083ddc75ad3b1003a46e5b0d@15.235.160.127:23856 (Asia_SE)

2023-12-21 08:41 UTC, nullmames commented on pages/networks/network1/resources.md
> +| gRPC  | `dydx-dao-grpc-1.polkachu.com:23890` <br> `dydx-dao-grpc-2.polkachu.com:23890` <br> `dydx-dao-grpc-3.polkachu.com:23890` <br> `dydx-dao-grpc-4.polkachu.com:23890` <br> `dydx-dao-grpc-5.polk
I would still include the transport protocol for these. `https` for nodes with port `443` and `http` for polkachu's nodes.

2024-01-05 15:26 UTC, dydxoperationstrust requested changes
`Also check [“Snapshot service → Snapshots]` no longer has the sub level `-> Snapshots`

2024-01-05 15:30 UTC, dydxoperationstrust approved these changes

2024-01-05 15:31 UTC, merged